/*
 * Copyright 2019 Mentor Graphics Corporation
 * All Rights Reserved
 *
 * THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY
 * INFORMATION WHICH IS THE PROPERTY OF MENTOR
 * GRAPHICS CORPORATION OR ITS LICENSORS AND IS
 * SUBJECT TO LICENSE TERMS.
 */

package chs.caplets.logic.actions.layout;

/**
 * @author chandras on 19-10-2019.
 */
public enum DeviceDecorationObjectType
{
	MAIN_COMPOUND_CONTAINER,
	SYM_GRID_TRUE_BOUNDARY,
	DEVICE_NAME_TEXT,
	SYMBOL_NAME_TEXT,
	SYM_GRID_MARGIN_BOUNDARY,
	PROHIBITION_CIRCLE,
	PROHIBITION_BACK_SLASH,
	PROHIBITION_FWD_SLASH,
}
