/*
 * Copyright 2006-2016 Mentor Graphics Corporation
 * All Rights Reserved
 *
 * THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY
 * INFORMATION WHICH IS THE PROPERTY OF MENTOR
 * GRAPHICS CORPORATION OR ITS LICENSORS AND IS
 * SUBJECT TO LICENSE TERMS.
 */
package chs.caplets.logic.actions;

import chs.ans.IObjectDescriptor;
import chs.caf.CAFUtils;
import chs.caf.cafmain.actions.CAFCommandHelper;
import chs.caf.caplet.ICapletController;
import chs.caf.caplet.action.IActionEnum;
import chs.caf.caplet.helpers.ControllerActionRT;
import chs.caf.caplet.helpers.UndoableContainerIdler;
import chs.caf.caplet.helpers.creation.CreateByPointAction;
import chs.caf.caplet.helpers.creation.SnapPoint;
import chs.caf.caplet.selection.SelectSet;
import chs.caf.caplet.selection.SelectedUIDObjectIterator;
import chs.caplets.logic.BasicAddPinListDialog;
import chs.cof.logical.ILogicDesign;
import chs.cof.logical.cable.HarnessConnectorGenerationEnum;
import chs.cof.logical.cable.IAbstractPin;
import chs.cof.logical.cable.IBackshell;
import chs.cof.logical.cable.IBlockDevice;
import chs.cof.logical.cable.IConnector;
import chs.cof.logical.cable.IDeviceOwned;
import chs.cof.logical.cable.IFunction;
import chs.cof.logical.cable.IGenericInlineConnector;
import chs.cof.logical.cable.IHarnessPlugConnector;
import chs.cof.logical.cable.IInterconnectObject;
import chs.cof.logical.cable.ILogicBlockDevice;
import chs.cof.logical.cable.IPinList;
import chs.cof.logical.cable.ISplice;
import chs.cof.logical.shared.ISharedPinReservationView;
import chs.cof.logical.shared.SharedPinHelper;
import chs.cof.parts.ILibraryBaseObject;
import chs.cof.parts.ILibraryCavityContainer;
import chs.cof.symbol.IBlock;
import chs.cof.symbol.ISymbolDef;
import chs.cof.symbol.ISymbolRef;
import chs.common.IDesignContainer;
import chs.common.IMultiSymbolledPinlist;
import chs.common.ISymbolledPin;
import chs.common.IUID;
import chs.common.IUIDObject;
import chs.ctf.caf.ui.IPlacementOptionParams;
import chs.ctf.caf.ui.PinListPlaceOptionParams;
import chs.ctf.caf.utils.IPinProxy;
import chs.system.FactoryMgr;
import chs.utilities.CollectionUtils;
import chs.utilities.ResourceMgr;
import chs.utilities.ui.MessageHelper;
import chs.utilities.ui.property.IBooleanProperty;
import chs.utility.helpers.BlockDeviceUnconnectedPinSelectionHelper;
import chs.utility.helpers.DesignSharedUsageHelper;
import chs.utility.helpers.LogicObjectLockFinder;
import chs.utility.logic.DesignHelper;
import chs.utility.logic.PinUtils;
import chs.utility.ui.SymbolProxy;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.awt.Component;
import java.awt.Cursor;
import java.awt.Frame;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Map;

/**
 * Adds an instance of an existing pinlist (device, splice, connector, etc) to a diagram.
 * <p>
 * The instance could either be added as parameterized object or a symbolled object.
 */
public class AddPinListAction extends ControllerActionRT
		implements MouseListener, MouseMotionListener, KeyListener
{

	protected ControllerActionRT subAction;
	private AddMultiSymbolledPinListDialog m_symbolledPLDialog;

	public AddPinListAction(ICapletController controller)
	{
		super(controller);
	}

	protected IActionEnum onActivate(ActionEvent e)
	{
		// invoke the "Place ..." dialog for this pinlist type
		subAction = null;
		IPinList pinlist = getOperand();
		if (pinlist == null) {
			// dts0100591493: preventive fix (not reproduced), however previous assert is useless
			// without this test:
			assert false : "dts0100591493: Please try and record the steps";
			return IActionEnum.eCanceled;
		}

		if (!LogicObjectLockFinder.tryEdit(pinlist)) {
			return IActionEnum.eCanceled;
		}
		//melmorsy - FEAT12331
		//If the pinlist is an automatically generated plug connector, then don't allow instantiation!
		if (pinlist instanceof IHarnessPlugConnector && ((IHarnessPlugConnector) pinlist).getGenerationType() ==
				HarnessConnectorGenerationEnum.TypeAutomaticallyGenerated &&
				((IDeviceOwned) pinlist).getOwner() != null) {
			showInformationMessage(CAFUtils.getInstance().getDialogFrame(),
					ResourceMgr.getString(AddPinListAction.class, "AddPinListAction.AutoGeneratedPlug.Header"),
					ResourceMgr.getString(AddPinListAction.class, "AddPinListAction.AutoGeneratedPlug.Message",
							pinlist.getName()));
			return IActionEnum.eCanceled;
		}
		// don't show the dialog for splice without symbol
		List<IAbstractPin> pins = new ArrayList<IAbstractPin>();
		//pinProxies store the proxies for the pins which dont have a cable part yet - coming from library definition
		List<IPinProxy> pinProxies = new ArrayList<IPinProxy>();
		boolean autogenerate = true;
		boolean reference = false;
		boolean placeAsStack = false;
		boolean placeAsGroup = false;
		boolean withConductor = false;
		ISymbolDef symDef = loadSymbolDef(pinlist);
		IBlock block = null;
		Map<IUID, ISymbolledPin> symbolpinMap = null;
		if (pinSelectionDialogRequired(pinlist)) {
			// get all the options from the dialog
			Frame frame = CAFUtils.getInstance().getDialogFrame();
			String title = AddPinListDialog.getTitle(pinlist);
			if (!loadSharedUsagesIfNeeded(pinlist, frame, title)) {
				return IActionEnum.eCanceled;
			}
			if (!(pinlist instanceof IFunction) && pinlist instanceof IMultiSymbolledPinlist) {
				m_symbolledPLDialog = getAddMultiSymbolledPinListDialog(frame, title);
				enableSymbolView(m_symbolledPLDialog);
				ISharedPinReservationView pinview =
						FactoryMgr.getCommonFactory().constructSharedPinReservationView(pinlist.getSharedPinList());
				if (!m_symbolledPLDialog.selectPinList((IMultiSymbolledPinlist) pinlist, pinview,
						createPlacementOptionParams(pinlist, null))) {
					return IActionEnum.eCanceled;
				}
				for (Object pin : getSelectedPins()) {
					if (pin instanceof IAbstractPin) {
						pins.add((IAbstractPin) pin);
					}
					else if (pin instanceof IPinProxy) {
						IAbstractPin pinObj = ((IPinProxy) pin).getCablePin();
						if (pinObj != null) {
							pins.add(pinObj);
						}
						else {
							pinProxies.add((IPinProxy) pin);
						}
					}
				}

				autogenerate = m_symbolledPLDialog.getAutoGenerate();
				reference = m_symbolledPLDialog.getReference();
				placeAsStack = m_symbolledPLDialog.getPlaceAsStack();
				placeAsGroup = m_symbolledPLDialog.getPlaceAsGroup();
				IBooleanProperty withConductorOption = m_symbolledPLDialog.getWithConductorOption();
				withConductor = withConductorOption != null && withConductorOption.getValue();
				SymbolProxy[] symbolInstances = m_symbolledPLDialog.getSelectedSymbolInstances();
				if (m_symbolledPLDialog.isSymbelSelectionSelected() && symbolInstances.length > 0) {
					SymbolProxy proxy = getProxyWithSymbolDef(symbolInstances);
					if (proxy == null || proxy.getSymbolDef() == null) {
						proxy = getProxyWithBlock(symbolInstances);
						if (proxy != null) {
							block = proxy.getBlock();
							symDef = proxy.getSymbolDef();
						}
					}
					else {
						symDef = proxy.getSymbolDef();
					}
					if (proxy != null) {
						symbolpinMap = proxy.getPinsMapping();
					}
				}
				else {
					symDef = null;
					block = null;
				}
			}
			else {
				List<IPinProxy> pinSelection = new ArrayList<IPinProxy>();
				if (pinlist instanceof IBlockDevice /*&& Environment.isDesignHierarchyEnabled()*/) {
					final IBlockDevice blockDevice = (IBlockDevice) pinlist;
					PlaceBlockPinDialog placeBlockDialog =
							new PlaceBlockPinDialog(frame, new AddBlockPinActionModel(blockDevice), true,
									createPlacementOptionParams(blockDevice, null));
					IAddPinView.Result addPinView = placeBlockDialog.showDialog();
					if (addPinView == IAddPinView.Result.CANCEL) {
						return IActionEnum.eCanceled;
					}
					pinSelection.addAll(placeBlockDialog.getPins());
					autogenerate = placeBlockDialog.getAutogenerate();
					placeAsStack = placeBlockDialog.isPlaceAsStack();
					placeAsGroup = placeBlockDialog.isPlaceAsGroup();
				}
				else {
					IPinInfoProvider dlg = getAddPinListDialog(frame, pinlist, symDef);
					if (!dlg.selectPinList()) {
						return IActionEnum.eCanceled;
					}

					//For ring terminal, cancel the action if the pin is not selected
					if (IConnector.Statics.isRingTerminalTypeConnector(pinlist) && dlg.getPins().isEmpty()) {
						return IActionEnum.eCanceled;
					}

					pinSelection = dlg.getPins();

					autogenerate = dlg.getAutogenerate();
					reference = dlg.getReference();
					placeAsStack = dlg.getPlaceAsStack();
					placeAsGroup = dlg.getPlaceAsGroup();
					symDef = dlg.getSymbol();  // might be a different symbol
					block = dlg.getBlock();
				}
				pinProxies.addAll(pinSelection);
			}
		}
		else {
			pins = CollectionUtils.createList(pinlist.getPins());
			if (!pins.isEmpty()) {
				//check for pinduplication.
				IDesignContainer designContainer = DesignHelper.getDesign(pinlist);
				if (designContainer != null) {
					for (IAbstractPin sPin : pins) {
						if (!PinUtils.isPinPlaceableInDesign(sPin, designContainer)) {
							return IActionEnum.eCanceled;
						}
					}
				}
			}
		}

		// forward the rest of the behaviour to the sub actions for adding an instance with/without a symbol
		if (symDef != null) {
			return activateAddWithSymbol(e, pinlist, symDef, block, symbolpinMap, reference, withConductor);
		}
		return activateAddWithoutSymbol(e, pinlist, pins, autogenerate, reference, placeAsStack, placeAsGroup,
				pinProxies, withConductor);
	}

	@NotNull protected IPlacementOptionParams createPlacementOptionParams(@NotNull IPinList pinList,
			@Nullable ISymbolDef symDef)
	{
		return new PinListPlaceOptionParams(pinList, symDef);
	}

	public SnapPoint snapWorldPoint(MouseEvent e, Point worldPt)
	{
		return subAction.snapWorldPoint(e, worldPt);
	}

	@NotNull
	protected AddMultiSymbolledPinListDialog getAddMultiSymbolledPinListDialog(Frame frame, String title)
	{
		return new AddMultiSymbolledPinListDialog(frame, title, true);
	}

	@NotNull protected IPinInfoProvider getAddPinListDialog(@Nullable Frame frame, @NotNull IPinList pinlist, @Nullable ISymbolDef symDef)
	{
		boolean displayAutoGenerateOption =
				pinlist instanceof IFunction || (pinlist instanceof IGenericInlineConnector);
		return new AddPinListDialog(frame, pinlist, symDef, displayAutoGenerateOption,
				createPlacementOptionParams(pinlist, symDef));
	}

	protected Collection<IPinProxy> getSelectedPins()
	{
		return m_symbolledPLDialog.getUsedPins();
	}

	protected void enableSymbolView(BasicAddPinListDialog m_symbolledPLDialog)
	{

	}

	private boolean loadSharedUsagesIfNeeded(IPinList pinlist, Frame frame, String title)
	{
		ILogicDesign logicDesign = pinlist.getLogicDesign();
		if (logicDesign != null && pinlist.getSharedPinList() != null) {
			String longDes = ResourceMgr
					.getString(AddPinListAction.class, "AddPinListAction.LoadUsage.progress.longDescription");
			boolean loadedDesignMgrs = DesignSharedUsageHelper.loadeUsagesWithProgressBar(logicDesign.getProject(),
					frame, SharedPinHelper.getLogicDesignsUsingSharedPinList(logicDesign, pinlist.getSharedPinList()),
					title, title + " - " + pinlist.getName(), longDes);

			return !loadedDesignMgrs;
		}
		return true;
	}

	@Nullable private SymbolProxy getProxyWithBlock(SymbolProxy[] instances)
	{
		for (SymbolProxy symbolProxy : instances) {
			if (symbolProxy.isBlock()) {
				return symbolProxy;
			}
		}
		return null;
	}

	@Nullable private SymbolProxy getProxyWithSymbolDef(SymbolProxy[] instances)
	{
		for (SymbolProxy symbolProxy : instances) {
			if (!symbolProxy.isBlock()) {
				return symbolProxy;
			}
		}
		return null;
	}

	/**
	 * Generic message showing mechanism overridable in sub class that doesn't show a prompt (e.g. Test action)
	 *
	 * @param parent Parent component for the message dialog
	 * @param heading Message heading
	 * @param message Message body
	 */
	protected void showInformationMessage(Component parent, String heading, String message)
	{
		// TODO jacobt unit tests : should we move this utility up to the base class?
		// it's here to allow unit tests on this action code
		// It may be more appropriate to change the behaviour of MessageHelper during tests
		// Otherwise we'll have every test action having to override it
		// Could make MessageHelper an abstract singleton?
		// Or we could have another class handle all dialogs produced by actions?
		// Or perhaps just move the business logic out of actions & into commands?
		// I think that dependency injection is probably the way to go for this and other cases...
		// But for now we're stuck with this here
		MessageHelper.showInformationMessage(parent, heading, message);
	}

	protected boolean pinSelectionDialogRequired(IPinList pinlist)
	{

		// Pin selection for everything except splice and ICX (?)
		if ((pinlist instanceof ISplice || pinlist instanceof IInterconnectObject)) {
			return false;
		}
		// don't show dialog if no pins at all and no symbol
		return pinlist.getNumPins() > 0 || hasLibraryCavities(pinlist) || isBlockAndPinSelectionRequired(pinlist) ||
				(pinlist instanceof IMultiSymbolledPinlist && ((IMultiSymbolledPinlist) pinlist).getNumSymbols() > 0);
	}

	protected boolean hasLibraryCavities(IPinList pinlist)
	{
		ILibraryBaseObject libObj = pinlist.getLibraryObject();
		return libObj instanceof ILibraryCavityContainer && ((ILibraryCavityContainer) libObj).getNumCavities() > 0;
	}

	private boolean isBlockAndPinSelectionRequired(IPinList pinlist)
	{
		if (pinlist instanceof ILogicBlockDevice) {
			IBlockDevice block = (IBlockDevice) pinlist;
			List<IObjectDescriptor> unconnectedPins =
					BlockDeviceUnconnectedPinSelectionHelper.getUnconnectedPins(block);
			return !unconnectedPins.isEmpty() || block.getNumPins() > 0;
		}
		return false;
	}

	protected IActionEnum activateAddWithSymbol(ActionEvent e, IPinList pinlist, ISymbolDef symDef, IBlock block,
			Map<IUID, ISymbolledPin> map, boolean reference, boolean withConductor)
	{
		AddSymbolledPinListAction action =
				createAddSymbolledPinListAction(getController(), pinlist, symDef, block, map, reference, withConductor);
		subAction = action; // must set subAction before activating it so events are forwarded
		return action.onActivate(e);
	}

	protected IActionEnum activateAddWithoutSymbol(ActionEvent e, IPinList pinlist, List<IAbstractPin> pins,
			boolean autogenerate, boolean reference, boolean placeAsStack, boolean placeAsGroup,
			List<IPinProxy> pinProxies, boolean withConductor)
	{
		assert pinlist != null;
		assert pins != null;

		// nothing wrong with explicit initialization
		//noinspection UnusedAssignment
		IActionEnum result = IActionEnum.eCanceled;
		if (pinlist instanceof ISplice) {
			AddParameterizedSpliceAction action = createAddSpliceAction(getController(), (ISplice) pinlist);
			subAction = action; // must set subAction before activating it so events are forwarded
			result = action.onActivate(e);
		}
		else {
			CreateParameterizedObjectAction action =
					createCreateParameterizedAction(pinlist, pins, autogenerate, reference, placeAsStack, placeAsGroup,
							pinProxies, withConductor);
			subAction = action; // must set subAction before activating it so events are forwarded
			result = action.onActivate(e);
		}
		return result;
	}

	protected AddSymbolledPinListAction createAddSymbolledPinListAction(ICapletController controller, IPinList pinlist,
			ISymbolDef symDef, IBlock block, Map<IUID, ISymbolledPin> map, boolean reference, boolean withConductor)
	{
		return new AddSymbolledPinListAction(controller, pinlist, symDef, block, map, reference);
	}

	protected AddParameterizedSpliceAction createAddSpliceAction(ICapletController controller, ISplice splice)
	{
		return new AddParameterizedSpliceAction(controller, splice);
	}

	protected CreateParameterizedObjectAction createPlaceInlineConnectorAction(ICapletController controller,
			IGenericInlineConnector connector,
			List<IAbstractPin> pins, boolean autogenerate, boolean reference, boolean groupPlacement,
			boolean placeAsStack, Collection<IPinProxy> pinProxies)
	{
		return new PlaceInlineConnectorAction(controller, connector, pins, autogenerate, reference, groupPlacement,
				placeAsStack, pinProxies);
	}

	protected CreateParameterizedObjectAction createAddParameterizedPinListAction(ICapletController controller,
			IPinList pinlist,
			List<IAbstractPin> pins, boolean autogenerate, boolean reference, boolean placeAsStack,
			boolean placeAsGroup,
			List<IPinProxy> pinProxies, boolean withConductor)
	{
		return new AddParameterizedPinListAction(getController(), pinlist, pins, autogenerate, reference, placeAsStack,
				placeAsGroup,
				pinProxies);
	}

	protected CreateParameterizedObjectAction createAddParameterizedRingTerminalAction(ICapletController controller,
			IPinList pinlist,
			List<IAbstractPin> pins, boolean autogenerate, boolean reference, List<IPinProxy> pinProxies)
	{
		return new AddParameterizedRingTerminalAction(getController(), pinlist, pins, autogenerate, reference,
				pinProxies);
	}

	private CreateParameterizedObjectAction createCreateParameterizedAction(IPinList pinlist, List<IAbstractPin> pins,
			boolean autogenerate, boolean reference, boolean placeAsStack, boolean placeAsGroup,
			List<IPinProxy> pinProxies, boolean withConductor)
	{
		if (pinlist instanceof IGenericInlineConnector) {
			return createPlaceInlineConnectorAction(getController(), (IGenericInlineConnector) pinlist, pins,
					autogenerate, reference, placeAsGroup, placeAsStack, pinProxies);
		}
		if (IConnector.Statics.isRingTerminalTypeConnector(pinlist)) {
			return createAddParameterizedRingTerminalAction(getController(), pinlist, pins, autogenerate, reference,
					pinProxies);
		}

		// this same action is used for all the other pinlists - should it be?
		return createAddParameterizedPinListAction(getController(), pinlist, pins, autogenerate, reference,
				placeAsStack, placeAsGroup, pinProxies, withConductor);
	}

	protected boolean onTerminate(boolean successful)
	{
		// terminate the appropriate sub-action
		boolean result = false;
		if (subAction instanceof AddInstanceAction) {
			// add as symbol
			result = ((AddInstanceAction) subAction).onTerminate(successful);
		}
		else if (subAction instanceof CreateByPointAction) {
			// add as parameterized instance
			result = ((CreateByPointAction) subAction).onTerminate(successful);
		}
		else if (subAction instanceof AddParameterizedSpliceAction) {
			// adds a parameterized splice instance - different sort of action / events
			//noinspection OverlyStrongTypeCast
			result = ((AddParameterizedSpliceAction) subAction).onTerminate(successful);
		}
		else if (subAction != null) {
			assert false : "Unknown sub-action " + subAction;
		}
		if (m_symbolledPLDialog != null) {
			// dts0100695613- the dialog contains a layer to draw the symbol on, to clean this layer, we should suspend
			// the undoable container so that internal objects wouldn't be added to the undo edit. Anyway, we are not
			// interested in any objects inside the dialog anymore.
			CAFUtils.getInstance().setTempUndoableContainer(UndoableContainerIdler.instance());
			m_symbolledPLDialog.cleanUp();
			// restore the original undoable edit.
			CAFUtils.getInstance().clearTempUndoableContainer();
		}
		cleanUp(successful);
		subAction = null;
		return result;
	}

	protected void cleanUp(boolean sucessful)
	{

	}

	public boolean isEnabled()
	{
		if (!getController().getCapletModel().isEditable()) {
			return false;
		}
		return getOperand() != null && super.isEnabled();
	}

	public String getActionUIClass()
	{
		return AddPinListActionUI.class.getName();
	}

	/**
	 * @return If only a single connectivity pinlist is selected, return it otherwise return null
	 */
	@Nullable protected IPinList getOperand()
	{
		IPinList pl = null;
		SelectSet selections = getController().getSelectMgr().getPreSelections();
		for (SelectedUIDObjectIterator it = selections.getSelectedUIDObjects(); it.hasNext(); ) {
			IUIDObject obj = it.getNext();
			if (obj instanceof IPinList) {
				if (pl == null) {
					pl = (IPinList) obj;
				}
				else {
					pl = null; // multiple connectivity pinlists selected ==> not enabled
					break;
				}
			}
		}
		if (pl instanceof IBackshell) {
			pl = null;
		}

		if (pl != null && LogicObjectLockFinder.isLogicObjectLockedInOtherSession(pl)) {
			pl = null;
		}
		return pl;
	}

	// TODO jacobt FEAT13040 : Move this lower in the action hierarachy?  It is overridden by the test action
	@Nullable protected ISymbolDef loadSymbolDef(IPinList pinlist)
	{
		ISymbolRef symRef = pinlist.getSymbolRef();
		if (symRef != null && !pinlist.isShared()) {
			// symbol def skeleton load time - use util to avoid temp objects here
			return CAFCommandHelper.loadSymbolDef(symRef.getSymbolUID(), false);
		}
		return null;
	}

	// TODO jacobt FEAT13040 : Refactor sub action / event handling into base class "CompoundControllerAction" say

	public void mouseClicked(MouseEvent e)
	{
		if (subAction instanceof MouseListener) {
			((MouseListener) subAction).mouseClicked(e);
		}
	}

	public void mousePressed(MouseEvent e)
	{
		if (subAction instanceof MouseListener) {
			((MouseListener) subAction).mousePressed(e);
		}
	}

	public void mouseReleased(MouseEvent e)
	{
		if (subAction instanceof MouseListener) {
			((MouseListener) subAction).mouseReleased(e);

			// TODO jacobt FEAT13040 : may need to clear the crap up from the activation like this
			// or perhaps we just put the UndoableContainerIdler around the whole of the activate?
//			// sometimes this action creates stuff a bit too early
//			// need to mess with CDH to avoid warnings about creating stuff before onTerminate
//			CreationDeletionHelper cdh = CreationDeletionHelper.getTheCreationHelper();
//			if (cdh.getPendingCount() > 0) {
//				assert newObjects.isEmpty();
//				newObjects.addAll(CollectionUtils.createList(cdh.getNewObjectsToProcess()));
//				cdh.clearNewObjects();
//			}
		}
	}

	public void mouseEntered(MouseEvent e)
	{
		if (subAction instanceof MouseListener) {
			((MouseListener) subAction).mouseEntered(e);
		}
	}

	public void mouseExited(MouseEvent e)
	{
		if (subAction instanceof MouseListener) {
			((MouseListener) subAction).mouseExited(e);
		}
	}

	public void mouseDragged(MouseEvent e)
	{
		if (subAction instanceof MouseMotionListener) {
			((MouseMotionListener) subAction).mouseDragged(e);
		}
	}

	public void mouseMoved(MouseEvent e)
	{
		if (subAction instanceof MouseMotionListener) {
			((MouseMotionListener) subAction).mouseMoved(e);
		}
	}

	public void keyTyped(KeyEvent e)
	{
		if (subAction instanceof KeyListener) {
			((KeyListener) subAction).keyTyped(e);
		}
	}

	public void keyPressed(KeyEvent e)
	{
		if (subAction instanceof KeyListener) {
			((KeyListener) subAction).keyPressed(e);
		}
	}

	public void keyReleased(KeyEvent e)
	{
		if (subAction instanceof KeyListener) {
			((KeyListener) subAction).keyReleased(e);
		}
	}

	public Cursor getCursor()
	{
		if (subAction != null) {
			return subAction.getCursor();
		}
		return super.getCursor();
	}

	@Override public boolean isInterruptable()
	{
		return true;
	}

	@Override public boolean shouldDisableUndoForNonUndoableChanges()
	{
		if (subAction != null) {
			return subAction.shouldDisableUndoForNonUndoableChanges();
		}
		return super.shouldDisableUndoForNonUndoableChanges();
	}
}
