/*
 * This material contains trade secrets or otherwise confidential information owned by
 * Siemens Industry Software Inc. or its affiliates (collectively, "SISW"), or its licensors.
 * Access to and use of this information is strictly limited as set forth in the Customer's
 * applicable agreements with SISW.
 *
 * Copyright 2022 Siemens
 */

({
    baseUrl: './s',
    mainConfigFile: './s/main.js',
    name: 'main',
    paths: {
        jquery: "empty:",
        underscore: "empty:",
        backbone: "empty:",
        LoadMask: 'LoadMask',
        CookieHandler: 'utilities/CookieHandler',
        Utils: 'utilities/Utils',
        MessagingUtils: 'utilities/MessagingUtils',
        TextStyler: 'utilities/TextStyler',
        utilities: 'reWork/utilities',
        splitPanelView: 'utilities/splitPanelView',
        publisherEvents: 'reWork/events/publisherEvents',
        applicationMediator: 'reWork/events/applicationMediator',
        filter: 'reports/filter',
        reportHandler: 'utilities/reportHandler',
        OptionExpression: 'OptionExpression',
        Variables: 'Variables',
        SVGEventHandler: 'SVGEventHandler',
        TwoDSVGEventHandler: 'TwoDSVGEventHandler',
        CrossHighlightHandler: 'CrossHighlightHandler',
        RenderConnectivity: 'RenderConnectivity',
        objectModel: 'reWork/dao/objectModel',
        objectFactory: 'reWork/dao/objectFactory',
        xmlDataLoaderImpl: 'reWork/dao/xmlDataLoaderImpl',
        dataLoader: 'reWork/dao/dataLoader',
        locationViews: 'reWork/dao/locationViews',
        languageDataLoader: 'reWork/dao/languageDataLoader',
        filter_filter: 'reWork/filters/filter',
        vinFilter: 'reWork/filters/vinFilter',
        languageFilter: 'reWork/filters/languageFilter',
        layoutManager: 'reWork/modules/layoutManager',
        optionFilterPanel: 'reWork/modules/optionFilterPanel',
        VINSearchHandler: 'VINSearchHandler',
        contentArea: 'reWork/framework/contentArea',
        toolTip: 'reWork/modules/toolTip',
        print: 'reWork/modules/print',
        printPdf: 'reWork/modules/printPdf',
        languageTranslator: 'reWork/modules/languageTranslator',
        svgDetailPanel: 'reWork/modules/svgDetailPanel',
        popoutHandler: 'reWork/modules/popoutHandler',
        configurationsManager: 'reWork/modules/configurationsManager',
        InteractiveBuilderUtility: 'InteractiveBuilderUtility',
        VehicleConfigObject: 'VehicleConfigObject',
        ConfigurationFilterPopup: 'ConfigurationFilterPopup',
        BaseInteractiveBuilder: 'BaseInteractiveBuilder',
        XrefFilterConfigurationFilterPanel: 'XrefFilterConfigurationFilterPanel',
        XRefFilterConfigurationFilterPopup: 'XRefFilterConfigurationFilterPopup',
        ConfigurationFilterPanel: 'ConfigurationFilterPanel',
        ConfigurationFilter: 'reWork/filters/configurationFilter',
        SignalRenderer: 'SignalRenderer',
        attributeParser: 'reWork/dao/attributeParser',
        features: 'features',
        docObjectPopover: 'documentObject/docObjectPopover',
        docReqHandler: 'documentRequestHandler/docReqHandler',
        ajax: 'utilities/ajax',
        Search: 'filters/Search',
        SearchUsingIndex: 'filters/SearchUsingIndex',
        PlainSearch: 'filters/PlainSearch',
        designObjectsDataLoader: 'views/designobjects/designObjectsDataLoader',
        requireLib: "libs/require",
        "titleupdater": "titleupdater",
        "views/viewer": "views/viewer",
        "views/viewer": "views/viewer",
        "views/navigationPanelView": "views/navigationPanelView",
        "views/systems": "views/systems",
        "views/informations": "views/informations",
        "views/commonFaultCode": "views/commonFaultCode",
        "views/harnessLayoutsView": "views/harnessLayoutsView",
        "views/harness": "views/harness",
        "views/faultCode": "views/faultCode",
        "views/diagnosticsView": "views/diagnosticsView",
        "views/paginatedListview": "views/paginatedListview",
        "views/designobjects/designObjectsSection": "views/designobjects/designObjectsSection",
        "views/globalReports": "views/globalReports",
        "views/contentpanel/contentPanel": "views/contentpanel/contentPanel",
        "views/contentpanel/toolbar/systemToolBar": "views/contentpanel/toolbar/systemToolBar",
        "views/contentpanel/toolbar/LayoutButtons": "views/contentpanel/toolbar/LayoutButtons",
        "views/contentpanel/toolbar/generalButtons": "views/contentpanel/toolbar/generalButtons",
        "views/contentpanel/toolbar/contentToolBar": "views/contentpanel/toolbar/contentToolBar",
        "views/zoomToolBarView": "views/zoomToolBarView",
        "views/contentpanel/systemDiagramPanel": "views/contentpanel/systemDiagramPanel",
        "views/contentpanel/systemReportPanel": "views/contentpanel/systemReportPanel",
        "views/contentpanel/reportView": "views/contentpanel/reportView",
        "views/contentpanel/locationViewPanel": "views/contentpanel/locationViewPanel",
        "views/contentpanel/harnessDiagramPanel": "views/contentpanel/harnessDiagramPanel",
        "views/contentpanel/harnessReportPanel": "views/contentpanel/harnessReportPanel",
        "views/contentpanel/renderedSVGPanel": "views/contentpanel/renderedSVGPanel",
        "views/contentpanel/faultCodePanel": "views/contentpanel/faultCodePanel",
        "views/contentpanel/diagnosticPanel": "views/contentpanel/diagnosticPanel",
        "views/contentpanel/customContentPanel": "views/contentpanel/customContentPanel",
        "views/contentpanel/faceViewPanel": "views/contentpanel/faceViewPanel",
        "views/contentpanel/threeDXMLPanel": "views/contentpanel/threeDXMLPanel",
        "views/contentpanel/rapidAuthorCatalogPanel": "views/contentpanel/rapidAuthorCatalogPanel",
        "views/packageView": "views/packageView",
        "views/filters/textSearchView": "views/filters/textSearchView",
        "views/filters/toastNotificationView": "views/filters/toastNotificationView",
        "views/p/designObjectPopoverView": "views/p/designObjectPopoverView",
        "views/p/locationViewPopoverView": "views/p/locationViewPopoverView",
        "views/p/xrefsView": "views/p/xrefsView",
        "views/p/harnessPopoverView": "views/p/harnessPopoverView",
        "views/p/attributesView": "views/p/attributesView",
        "views/p/groundSignalPopoverItem": "views/p/groundSignalPopoverItem",
        "views/p/connectorFaceviewView": "views/p/connectorFaceviewView",
        "views/p/threeDviewView": "views/p/threeDviewView",
        "views/p/customDataView": "views/p/customDataView",
        "views/p/twoDLocationView": "views/p/twoDLocationView",
        "views/p/print/printOptionsPopoverView": "views/p/print/printOptionsPopoverView",
        "views/p/print/printOptionsPopoverItemView": "views/p/print/printOptionsPopoverItemView",
        "views/p/print/printContentPopoverView": "views/p/print/printContentPopoverView",
        "views/p/print/printContentPopoverItemView": "views/p/print/printContentPopoverItemView",
        "views/p/diagrams/diagramsPopoverView": "views/p/diagrams/diagramsPopoverView",
        "views/p/diagrams/diagramPopoverItemView": "views/p/diagrams/diagramPopoverItemView",
        "views/p/languages/languagesPopoverView": "views/p/languages/languagesPopoverView",
        "views/p/languages/languagesPopoverItemView": "views/p/languages/languagesPopoverItemView",
        "views/p/reports/reportsPopoverView": "views/p/reports/reportsPopoverView",
        "views/p/reports/reportsPopoverItemView": "views/p/reports/reportsPopoverItemView",
        "views/p/relatedData/relatedDataPopoverView": "views/p/relatedData/relatedDataPopoverView",
        "views/p/relatedData/objSecView": "views/p/relatedData/objSecView",
        "views/filters/vin/vinFilterView": "views/filters/vin/vinFilterView",
        "views/filters/vin/vinLoginPopoverView": "views/filters/vin/vinLoginPopoverView",
        "views/p/c/configurationsView": "views/p/c/configurationsView",
        "views/p/c/xRefsBuilderView": "views/p/c/xRefsBuilderView",
        "views/p/c/configurationsPanelView": "views/p/c/configurationsPanelView",
        "views/p/c/optionsPanelView": "views/p/c/optionsPanelView",
        "views/customProjectDataListView": "views/customProjectDataListView",
        "views/p/relatedData/customDataView": "views/p/relatedData/customDataView",
        "views/p/hld/HarnessLayoutDiagramsPopover": "views/p/hld/HarnessLayoutDiagramsPopover",
        "views/p/hld/HarnessLayoutDiagramsPanel": "views/p/hld/HarnessLayoutDiagramsPanel",
        "views/p/colors/colorspopover": "views/p/colors/colorspopover",
        "views/p/colors/palettepanel": "views/p/colors/palettepanel",
        "views/p/colors/historypanel": "views/p/colors/historypanel",
        "utilities/pagination": "utilities/pagination",
        "filehandlers/effectivitySetter": "filehandlers/effectivitySetter",
        "routers/projectDataRouter": "routers/projectDataRouter",
        "routers/locationViewRouter": "routers/locationViewRouter",
        "routers/systemReportRouter": "routers/systemReportRouter",
        "routers/systemRouter": "routers/systemRouter",
        "routers/customPluginRouter": "routers/customPluginRouter",
        "routers/powerToGroundRouter": "routers/powerToGroundRouter",
        "routers/objectConnectivityRouter": "routers/objectConnectivityRouter",
        "routers/objectFaceViewRouter": "routers/objectFaceViewRouter",
        "routers/object3DViewRouter": "routers/object3DViewRouter",
        "routers/multipleDocumentRouter": "routers/multipleDocumentRouter",
        "routers/harnessLayoutDiagramRouter": "routers/harnessLayoutDiagramRouter",
        "filehandlers/systemSVGHandler": "filehandlers/systemSVGHandler",
        "viewModels/reportPopoutViewModel": "viewModels/reportPopoutViewModel",
        "SVGElementVisibilityToggler": "SVGElementVisibilityToggler",
        "baseTreeView": "empty:",
    },
    include: [
        'utilities/pagination',
        'URLQueryParameterHandler',
        'requireLib',
        'LoadMask',
        'CookieHandler',
        'Utils',
        'MessagingUtils',
        'TextStyler',
        'utilities',
        'splitPanelView',
        'publisherEvents',
        'applicationMediator',
        'filter',
        'reportHandler',
        'OptionExpression',
        'Variables',
        'SVGEventHandler',
        'TwoDSVGEventHandler',
        'CrossHighlightHandler',
        'RenderConnectivity',
        'objectModel',
        'objectFactory',
        'xmlDataLoaderImpl',
        'dataLoader',
        'locationViews',
        'languageDataLoader',
        'filter_filter',
        'vinFilter',
        'languageFilter',
        'layoutManager',
        'optionFilterPanel',
        'VINSearchHandler',
        'contentArea',
        'toolTip',
        'print',
        'printPdf',
        'languageTranslator',
        'svgDetailPanel',
        'popoutHandler',
        'configurationsManager',
        'InteractiveBuilderUtility',
        'VehicleConfigObject',
        'ConfigurationFilterPopup',
        'BaseInteractiveBuilder',
        'XrefFilterConfigurationFilterPanel',
        'XRefFilterConfigurationFilterPopup',
        'ConfigurationFilterPanel',
        'SignalRenderer',
        'attributeParser',
        'features',
        'docObjectPopover',
        'docReqHandler',
        'ajax',
        'Search',
        'SearchUsingIndex',
        'PlainSearch',
        'designObjectsDataLoader',
        "views/viewer",
        "views/navigationPanelView",
        "views/systems",
        "views/informations",
        "views/commonFaultCode",
        "views/harnessLayoutsView",
        "views/harness",
        "views/faultCode",
        "views/diagnosticsView",
        "views/diagnosticsTreeView",
        "views/paginatedListview",
        "views/globalReports",
        "views/designobjects/designObjectsSection",
        "views/contentpanel/contentPanel",
        "views/contentpanel/toolbar/systemToolBar",
        "views/contentpanel/toolbar/LayoutButtons",
        "views/contentpanel/toolbar/generalButtons",
        "views/contentpanel/toolbar/contentToolBar",
        "views/zoomToolBarView",
        "views/contentpanel/systemDiagramPanel",
        "views/contentpanel/systemReportPanel",
        "views/contentpanel/reportView",
        "views/contentpanel/locationViewPanel",
        "views/contentpanel/harnessDiagramPanel",
        "views/contentpanel/harnessReportPanel",
        "views/contentpanel/renderedSVGPanel",
        "views/contentpanel/faultCodePanel",
        "views/contentpanel/diagnosticPanel",
        "views/contentpanel/customContentPanel",
        "views/contentpanel/faceViewPanel",
        "views/contentpanel/threeDXMLPanel",
        "views/contentpanel/rapidAuthorCatalogPanel",
        "views/packageView",
        "views/filters/textSearchView",
        "views/filters/toastNotificationView",
        "views/p/designObjectPopoverView",
        "views/p/locationViewPopoverView",
        "views/p/xrefsView",
        "views/p/harnessPopoverView",
        "views/p/attributesView",
        "views/p/groundSignalPopoverItem",
        "views/p/connectorFaceviewView",
        "views/p/threeDviewView",
        "views/p/customDataView",
        "views/p/twoDLocationView",
        "views/p/print/printOptionsPopoverView",
        "views/p/print/printOptionsPopoverItemView",
        "views/p/print/printContentPopoverView",
        "views/p/print/printContentPopoverItemView",
        "views/p/diagrams/diagramsPopoverView",
        "views/p/diagrams/diagramPopoverItemView",
        "views/p/languages/languagesPopoverView",
        "views/p/languages/languagesPopoverItemView",
        "views/p/reports/reportsPopoverView",
        "views/p/reports/reportsPopoverItemView",
        "views/p/relatedData/relatedDataPopoverView",
        "views/p/relatedData/objSecView",
        "views/p/relatedData/objSecView",
        "views/p/relatedData/objSecView",
        "views/filters/vin/vinFilterView",
        "views/filters/vin/vinLoginPopoverView",
        "views/p/c/configurationsView",
        "views/p/c/xRefsBuilderView",
        "views/p/c/configurationsPanelView",
        "views/p/c/optionsPanelView",
        "views/customProjectDataListView",
        "views/p/relatedData/customDataView",
        "views/p/hld/HarnessLayoutDiagramsPopover",
        "views/p/hld/HarnessLayoutDiagramsPanel",
        "views/p/colors/colorspopover",
        "views/p/colors/palettepanel",
        "views/p/colors/historypanel",
        "titleupdater",
        'ConfigurationFilter',
        "views/homeView",
        "views/projectsView",
        "views/packagesView",
        "views/packageInfoView",
        "views/homeMenu",
        "views/p/settings/SettingsPopoverView",
        "SystemScopePanel",
        "LanguagesPanel",
        "views/p/projects/ProjectsPopoverView",
        "ProjectsPanel",
        "filehandlers/effectivitySetter",
        "routers/projectDataRouter",
        "routers/locationViewRouter",
        "routers/systemReportRouter",
        "routers/systemRouter",
        "routers/customPluginRouter",
        "routers/powerToGroundRouter",
        "routers/objectConnectivityRouter",
        "routers/objectFaceViewRouter",
        "routers/object3DViewRouter",
        "routers/multipleDocumentRouter",
        "routers/harnessLayoutDiagramRouter",
        "filehandlers/systemSVGHandler",
        "viewModels/reportPopoutViewModel",
        "SVGElementVisibilityToggler",
        "LocalConfigurations",
        "collections/faults",
        "collections/commonFaultCode",
        "routers/troubleshootRouter",
        "views/troubleshoot/troubleshootPanel"
    ],
    optimize: "uglify2",
    inlineText: false,
    useStrict: true,
    uglify2: {
        output: {
            beautify: false
        },
        mangle: false
    }
});