/*
 * Copyright 2021 Mentor Graphics Corporation
 * All Rights Reserved
 *
 * THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY
 * INFORMATION WHICH IS THE PROPERTY OF MENTOR
 * GRAPHICS CORPORATION OR ITS LICENSORS AND IS
 * SUBJECT TO LICENSE TERMS.
 */

// Karma configuration
// Generated on Fri Aug 06 2021 09:27:48 GMT+0530 (India Standard Time)

module.exports = function (config) {
    config.set({

        // base path that will be used to resolve all patterns (eg. files, exclude)
        basePath: '.',


        // frameworks to use
        // available frameworks: https://www.npmjs.com/search?q=keywords:karma-adapter
        frameworks: ['jasmine'],


        // list of files / patterns to load in the browser
        files: [
            {pattern: 's/libs/text.js', included: false},
            'test/tests-requireJS/libs/sinon.js',
            'test/tests-requireJS/libs/sinon/spy.js',
            'test/tests-requireJS/libs/sinon/call.js',
            'test/tests-requireJS/libs/sinon/stub.js',
            'test/tests-requireJS/libs/sinon/util/fake_timers.js',
            'test/tests-requireJS/libs/jquery.js',
            // lib files
            //'s/libs/require.js', // Not required because it is already a framework dependency
            's/libs/underscore.js',
            's/libs/backbone.js',
            'node_modules/requirejs/require.js',
            'node_modules/karma-requirejs/lib/adapter.js',

            // Order or following files is important
            's/utilities/Utils.js',
            's/utilities/MessagingUtils.js',
            's/utilities/TextStyler.js',
            's/reWork/utilities.js',
            's/utilities/splitPanelView.js',
            's/reWork/events/publisherEvents.js',
            's/features.js',
            's/reWork/events/applicationMediator.js',
            's/OptionExpression.js',
            'test-main.js',
            's/utilities/CookieHandler.js',
            's/Variables.js',
            's/SVGEventHandler.js',
            's/reWork/framework/contentArea.js',
            's/reWork/filters/vinFilter.js',
            's/reWork/filters/configurationFilter.js',
            's/reWork/filters/filter.js',
            's/reWork/dao/languageDataLoader.js',
            's/reWork/filters/languageFilter.js',
            's/reWork/modules/layoutManager.js',
            's/reWork/modules/languageTranslator.js',
            's/reWork/modules/svgDetailPanel.js',

            's/VINSearchHandler.js',
            's/reWork/modules/print.js',
            's/utilities/reportHandler.js',
            's/reWork/modules/toolTip.js',
            's/reWork/dao/locationViews.js',
            's/reWork/dao/objectFactory.js',
            's/reWork/dao/xmlDataLoaderImpl.js',
            's/CrossHighlightHandler.js',
            's/RenderConnectivity.js',
            's/documentRequestHandler/docReqHandler.js',
            's/TwoDSVGEventHandler.js',
            's/SignalRenderer.js',
            's/reWork/modules/popoutHandler.js',
            's/reWork/modules/optionFilterPanel.js',
            's/documentObject/docObjectPopover.js',
            's/utilities/ajax.js',
            's/filters/Search.js',
            's/filters/SearchUsingIndex.js',
            's/filters/PlainSearch.js',
            's/views/designobjects/designObjectsDataLoader.js',
            's/LoadMask.js',
            's/VehicleConfigObject.js',
            's/BaseInteractiveBuilder.js',
            's/ConfigurationFilterPanel.js',
            's/ConfigurationFilterPopup.js',
            's/reWork/modules/configurationsManager.js',
            's/templates/projectsViewTemplate.html',
            's/templates/packagesViewTemplate.html',
            's/templates/popup/systemToolBar.html',
            's/templates/cp/toolbar/systemToolBar.html',
            's/templates/ErrorTemplate.html',
            's/templates/p/printTemplate.html',
            's/templates/wiresViewsTemplate.html',
            's/templates/paginatedListGroup.html',
            's/templates/warningTemplate.html',
            's/templates/informationTemplate.html',
            's/templates/packageInfoViewTemplate.html',
            's/templates/flatListTemplate.html',
            's/templates/p/attributesTemplate.html',
            's/templates/p/basicListItemTemplate.html',
            's/templates/p/twoDLocationsTemplate.html',
            's/templates/p/popoverTemplate.html',
            's/templates/p/multipleListItemsTemplate.html',
            's/templates/p/c/configPopupBtnControls.html',
            's/templates/packagesTemplate.html',
            's/templates/popupTemplate.html',
            's/templates/cp/RA3DTemplate.html',
            's/templates/troubleshoot/troubleshootPanel.html',
            's/templates/troubleshoot/faultCodeSelection.html',
            's/templates/troubleshoot/faultObjectsTable.html',
            's/templates/troubleshoot/faultObjectsTablePopout.html',
            's/templates/component/indeterminateProgressDialog.html',
            's/templates/troubleshoot/faultsTable.html',
            'noLicence.html',
            {pattern: 's/collections/sectionCollection.js', included: false},
            {pattern: 's/filters/textSearch.js', included: false},
            {pattern: 's/collections/systems.js', included: false},
            {pattern: 's/collections/harnesses.js', included: false},
            {pattern: 's/collections/panelDataCollection.js', included: false},
            {pattern: 's/collections/locationViews.js', included: false},
            {pattern: 's/filehandlers/fileHandlers.js', included: false},
            {pattern: 's/models/Package.js', included: false},
            {pattern: 's/models/p/diagrams/diagramsPopoverModel.js', included: false},
            {pattern: 's/models/p/relatedData/relatedDataPopoverModel.js', included: false},
            {pattern: 's/models/p/reports/reportsPopoverModel.js', included: false},
            {pattern: 's/models/p/popoverModel.js', included: false},
            {pattern: 's/collections/p/diagrams/diagramsCollection.js', included: false},
            {pattern: 's/collections/p/reports/reportsCollection.js', included: false},
            {pattern: 's/collections/p/popoverItemCollection.js', included: false},
            {pattern: 's/models/p/popoverFilterModel.js', included: false},
            {pattern: 's/models/c/XRefActiveConfigModel.js', included: false},
            {pattern: 's/models/zoomToolBarModel.js', included: false},
            {pattern: 's/models/ra3DModel.js', included: false },
            {pattern: 's/models/base3DModel.js', included: false },
            {pattern: 's/views/ListView.js', included: false},
            {pattern: 's/views/designObjectsView.js', included: false},
            {pattern: 's/views/p/XRefsViewItem.js', included: false},
            {pattern: 's/collections/p/attributesCollection.js', included: false},
            {pattern: 's/collections/p/connectorFaceviewCollection.js', included: false},
            {pattern: 's/collections/p/threeDViewCollection.js', included: false},
            {pattern: 's/collections/p/twoDLocationCollection.js', included: false},
            {pattern: 's/collections/p/customDataCollection.js', included: false},
            {pattern: 's/collections/faultCodes.js', included: false},
            {pattern: 's/collections/p/xrefsCollection.js', included: false},
            {pattern: 's/models/ra3DModel.js', included: false},
            {pattern: 's/models/base3DModel.js', included: false},
            {pattern: 's/collections/p/c/*.js', included: false},
            {pattern: 's/collections/faults.js', included: false},
            {pattern: 's/collections/faultSignals.js',included: false},
            {pattern: 's/models/troubleshoot/FaultCodesModel.js', included: false},
            {pattern: 's/models/troubleshoot/guidedDiagnosticsConfig.js', included: false},
            {pattern: 's/functions/troubleshoot/generateDiagram.js', included: false},
            {pattern: 's/functions/troubleshoot/getFaultObjectsTableColumnBasedComparator.js', included: false},
            {pattern: 's/functions/troubleshoot/computeFaultObjects.js', included: false},
            {pattern: 's/functions/troubleshoot/openGuidedDiagnostics.js', included: false},
            {pattern: 's/views/component/IndeterminateProgressDialog.js', included: false},
            {pattern: 's/functions/troubleshoot/getFaultTableColumnBasedComparator.js', included: false},
            {pattern: 's/collections/p/languages/*.js', included: false},
            {pattern: 's/collections/p/packages/packagesCollection.js', included: false},
            {pattern: 's/collections/p/print/*.js', included: false},
            {pattern: 's/models/p/locationViewObjectPopoverModel.js', included: false},
            {pattern: 's/views/p/popoverItemView.js', included: false},
            {pattern: 's/routers/componentRouter.js', included: false},
            {pattern: 's/views/listGroupView.js', included: false},
            {pattern: 's/views/p/BasicPopoverView.js', included: false},
            {pattern: 's/views/p/popoverView.js', included: false},
            {pattern: 's/collections/harnessLayouts.js', included: false},
            {pattern: 's/models/currentPackage.js', included: false},
            {pattern: 's/models/signalTracerModel.js', included: false},
            {pattern: 's/models/svg/ZoomAndPanModule.js', included: false},
            {pattern: 's/models/store/LocalStoragePersistenceModel.js', included: false},
            {pattern: 's/models/store/CookieBasedePersistenceModel.js', included: false},
            {pattern: 's/models/store/RemoteStoragePersistenceModel.js', included: false},
            {pattern: 's/models/store/PersistenceModelFactory.js', included: false},
            {pattern: 's/models/svg/SVGTransformModel.js', included: false},
            {pattern: 's/models/svg/SelectedObjectsStore.js', included: false},
            {pattern: 's/models/Project.js', included: false},
            {pattern: 's/models/Effectivity.js', included: false},
            {pattern: 's/models/UserSession.js', included: false},
            {pattern: 's/collections/Projects.js', included: false},
            {pattern: 's/collections/Packages.js', included: false},
            {pattern: 's/models/PackagesInSession.js', included: false},
            {pattern: 's/views/treeViewHelper.js', included: false},
            {pattern: 's/views/dragController.js', included: false},
            {pattern: 's/custom/treeViews/s/baseTreeView.js', included: false},
            {pattern: 's/custom/treeViews/s/systemsAsTreeView.js', included: false},
            {pattern: 's/views/p/c/baseConfigurationsBuilderView.js', included: false},
            {pattern: 's/models/c/configurationsModel.js', included: false},
            {pattern: 's/models/c/baseConfigurationsModel.js', included: false},
            {pattern: 's/models/c/xRefBuilderModel.js', included: false},
            {pattern: 's/views/p/c/xRefsBuilderView.js', included: false},
            {pattern: 's/router.js', included: false},
            {pattern: 's/routers/multipleDocumentRouter.js', included: false},
            {pattern: 's/routers/harnessLayoutDiagramRouter.js', included: false},
            {pattern: 's/models/p/designObjectPopoverModel.js', included: false},
            {pattern: 's/views/p/groundSignalPopoverItem.js', included: false},
            {pattern: 's/collections/informations.js', included: false},
            {pattern: 's/views/contentpanel/customContentPanel.js', included: false},
            {pattern: 's/views/contentpanel/toolbar/contentToolBar.js', included: false},
            {pattern: 's/views/contentpanel/toolbar/systemToolBar.js', included: false},
            {pattern: 's/views/contentpanel/toolbar/generalButtons.js', included: false},
            {pattern: 's/views/contentpanel/designReportPanel.js', included: false},
            {pattern: 's/views/contentpanel/faceViewPanel.js', included: false},
            {pattern: 's/views/contentpanel/faultCodePanel.js', included: false},
            {pattern: 's/views/contentpanel/locationViewPanel.js', included: false},
            {pattern: 's/views/contentpanel/threeDXMLPanel.js', included: false},
            {pattern: 's/views/contentpanel/systemReportPanel.js', included: false},
            {pattern: 's/views/contentpanel/systemDiagramPanel.js', included: false},
            {pattern: 's/views/zoomToolBarView.js', included: false},
            {pattern: 's/views/systems.js', included: false},
            {pattern: 's/views/informations.js', included: false},
            {pattern: 's/models/detailsPanelModel.js', included: false},
            {pattern: 's/views/p/xrefsView.js', included: false},
            {pattern: 's/views/p/twoDLocationView.js', included: false},
            {pattern: 's/views/p/attributesView.js', included: false},
            {pattern: 's/views/p/connectorFaceviewView.js', included: false},
            {pattern: 's/views/p/threeDviewView.js', included: false},
            {pattern: 's/views/p/customDataView.js', included: false},
            {pattern: 's/views/contentpanel/rapidAuthorCatalogPanel.js', included: false},
            {pattern: 's/collections/p/groundPathCollection.js', included: false},
            {pattern: 's/collections/p/xrefsCollectionItem.js', included: false},
            {pattern: 's/views/p/diagrams/diagramPopoverItemView.js', included: false},
            {pattern: 's/views/p/languages/languagesPopoverItemView.js', included: false},
            {pattern: 's/views/p/reports/reportsPopoverItemView.js', included: false},
            {pattern: 's/views/p/print/printOptionsPopoverItemView.js', included: false},
            {pattern: 's/views/contentpanel/SVGContentPanel.js', included: false},
            {pattern: 's/views/troubleshoot/faultCodeSelectionView.js', included: false},
            {pattern: 's/views/troubleshoot/FaultsTable.js', included: false},
            {pattern: 's/views/troubleshoot/FaultObjectsTable.js', included: false},
            {pattern: 's/views/troubleshoot/troubleshootPanel.js', included: false},
            {pattern: 's/routers/systemRouter.js', included: false},
            {pattern: 's/routers/systemReportRouter.js', included: false},
            {pattern: 's/routers/projectDataRouter.js', included: false},
            {pattern: 's/routers/objectFaceViewRouter.js', included: false},
            {pattern: 's/routers/object3DViewRouter.js', included: false},
            {pattern: 's/views/contentpanel/contentPanel.js', included: false},
            {pattern: 's/views/customProjectDataListView.js', included: false},
            {pattern: 's/views/filters/vin/vinFilterView.js', included: false},
            {pattern: 's/preferences.js', included: false},
            {pattern: 's/utilities/TranslationUtils.js', included: false},
            {pattern: 's/views/navigationPanelView.js', included: false},
            {pattern: 's/models/HarnessLayout.js', included: false},
            {pattern: 's/views/contentpanel/harnessReportPanel.js', included: false},
            {pattern: 's/views/contentpanel/reportView.js', included: false},
            {pattern: 's/views/contentpanel/toolbar/LayoutButtons.js', included: false},
            {pattern: 's/models/Layout.js', included: false},
            {pattern: 's/views/contentpanel/DefaultBarHandler.js', included: false},
            {pattern: 's/views/contentpanel/harnessLayoutBarHandler.js', included: false},
            {pattern: 's/collections/harnessPopoverColl.js', included: false},
            {pattern: 's/views/p/harnessPopoverView.js', included: false},
            {pattern: 's/views/p/basicPopoverView.js', included: false},
            {pattern: 's/views/p/relatedData/relatedDataPopoverView.js', included: false},
            {pattern: 's/views/packageView.js', included: false},
            {pattern: 's/views/renderconnectivity/buildBtnView.js', included: false},
            {pattern: 's/views/appNameAndLogo/appNameAndLogoView.js', included: false},
            {pattern: 's/internalLinkHandler.js', included: false},
            {pattern: 's/models/navPanelModel.js', included: false},
            {pattern: 's/URLQueryParameterHandler.js', included: false},
            {pattern: 's/models/faceviews.js', included: false},
            {pattern: 's/models/selectedSystem.js', included: false},
            {pattern: 's/views/p/colors/palettepanel.js', included: false},
            {pattern: 's/views/p/colors/historypanel.js', included: false},
            {pattern: 's/views/p/colors/colorspopover.js', included: false},
            {pattern: 's/models/p/colors/recentcolors.js', included: false},
            {pattern: 's/utilities/SVGTransforms.js', included: false},
            {pattern: 's/viewModels/PackagesViewModel.js', included: false},
            {pattern: 's/viewModels/ProjectsViewModel.js', included: false},
            {pattern: 's/filters/documentContentBasedFilter.js', included: false},
            {pattern: 's/filters/attributeBasedFilter.js', included: false},
            {pattern: 's/views/filteredDocFinder.js', included: false},
            {pattern: 's/illustrator/templates/*.html', included: false},
            {pattern: 's/illustrator/**/*.js', included: false},
            {pattern: 's/views/contentpanel/harnessDiagramPanel.js', included: false},
            {pattern: 's/views/contentpanel/HarnessDesignPanel.js', included: false},
            {pattern: 's/filehandlers/systemSVGHandler.js', included: false},
            { pattern: 's/views/p/c/configurationsView.js', included: false },
            { pattern: 's/views/p/c/configurationsPanelView.js', included: false },
            { pattern: 's/views/designobjects/**/*.js', included: false },
            { pattern: 's/utilities/pagination.js', included: false },
            { pattern: 's/views/component/*.js', included: false },
            { pattern: 's/viewModels/reportViewModel.js', included: false },
            { pattern: 's/filehandlers/effectivitySetter.js', included: false },
            { pattern: 's/collections/SubPackages.js', included: false },
            { pattern: 's/models/SubPackage.js', included: false },
            { pattern: 's/views/packagesView.js', included: false },
            's/reWork/dao/attributeParser.js',
            {pattern: 'test/tests-requireJS/illustrator/tests/*Test.js', included: false},
            {pattern: 'test/tests-requireJS/collections/collectionTest.js', included: false},
            'test/tests-requireJS/models/signalTracerModelTest.js',
            { pattern: 'test/tests-requireJS/views/designobjects/**/*.js', included: false },
            { pattern: 'test/tests-requireJS/views/popover/configurations/configurationsPanelViewTest.js', included: false },
            { pattern: 'test/tests-requireJS/views/popover/configurations/configurationsViewTest.js', included: false },
            // { pattern: 'test/tests-requireJS/routers/multipleDocumentsRouterTest.js', included: false },
            // { pattern: 'test/tests-requireJS/illustrator/templates/*Test.js', included: false },
            {pattern: 'test/tests-requireJS/viewmodels/projectsviewmodeltest.js', included: false},
            {pattern: 'test/tests-requireJS/viewmodels/packagesviewmodeltest.js', included: false},
            {pattern: 'test/tests-requireJS/viewmodels/packagesViewModelWithEffectivityTest.js', included: false},
            {pattern: 'test/tests-requireJS/lib/svgtransformstest.js', included: false},
            {pattern: 'test/tests-requireJS/models/popover/colors/recentcolorstest.js', included: false},
            {pattern: 'test/tests-requireJS/views/popover/colors/colorspopovertest.js', included: false},
            {pattern: 'test/tests-requireJS/views/popover/colors/historypaneltest.js', included: false},
            {pattern: 'test/tests-requireJS/views/popover/colors/palettepaneltest.js', included: false},
            {pattern: 'test/tests-requireJS/collections/popover/diagrams/diagramsCollectionTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/popover/groundSignalPopoverItemTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/troubleshoot/faultCodeSelectionViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/troubleshoot/faultObjectsTableTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/troubleshoot/faultsTableTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/troubleshoot/troubleshootingPanelTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/contentpanel/reports/harnessReportPanelTest.js', included: false},
            {
                pattern: 'test/tests-requireJS/views/contentpanel/reports/toolbar/harnesssLayoutBarHandlerTest.js',
                included: false
            },
            {pattern: 'test/tests-requireJS/collections/harness/harnessPopoverCollTest.js', included: false},
            {pattern: 'test/tests-requireJS/ContentAreaTest.js', included: false},
            {pattern: 'test/tests-requireJS/collections/sectionCollectionTest.js', included: false},
            {pattern: 'test/tests-requireJS/textSearchTest.js', included: false},
            {pattern: 'test/tests-requireJS/collections/systemsTest.js', included: false},
            {pattern: 'test/tests-requireJS/collections/informationCollectionTest.js', included: false},
            {pattern: 'test/tests-requireJS/collections/harnessesCollectionTest.js', included: false},
            {pattern: 'test/tests-requireJS/collections/locationViewsCollectionTest.js', included: false},
            {pattern: 'test/tests-requireJS/collections/DesignObjectsTest.js', included: false},
            {pattern: 'test/tests-requireJS/collections/packagesTest.js', included: false},
            {pattern: 'test/tests-requireJS/collections/SubPackagesTest.js', included: false},
            {pattern: 'test/tests-requireJS/fileHandlerTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/contentpanel/customContentPanelTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/contentpanel/faceViewContentPanelTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/contentpanel/faultCodePanelTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/contentpanel/locationViewPanelTest.js', included: false},
            { pattern: 'test/tests-requireJS/views/contentpanel/rapidAuthorCatalogPanelTest.js', included: false },
            // { pattern: 'test/tests-requireJS/views/contentpanel/threeDXMLPanelTest.js', included: false },
            {pattern: 'test/tests-requireJS/views/contentpanel/systemReportPanelTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/contentpanel/systemDiagramPanelTest.js', included: false},
            {pattern: 'test/tests-requireJS/faultCodesTest.js', included: false},
            {pattern: 'test/tests-requireJS/collections/popover/popoverAttributesCollectionTest.js', included: false},
            {pattern: 'test/tests-requireJS/models/detailsPanelModelTest.js', included: false},
            {pattern: 'test/tests-requireJS/collections/popover/popoverItemCollectionTest.js', included: false},
            {pattern: 'test/tests-requireJS/models/selectedSystemTest.js', included: false},
            {pattern: 'test/tests-requireJS/models/zoomToolBarModelTest.js', included: false},
            {pattern: 'test/tests-requireJS/models/faceViewsModelTest.js', included: false},
            {pattern: 'test/tests-requireJS/models/popover/popoverModelTest.js', included: false},
            {pattern: 'test/tests-requireJS/models/popover/locationViewObjectPopoverModelTest.js', included: false},
            {pattern: 'test/tests-requireJS/models/popover/designObjectPopoverModelTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/popover/popoverItemViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/popover/xrefsViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/popover/twoDLocationViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/popover/attributeViewTest.js', included: false},
            { pattern: 'test/tests-requireJS/views/popover/harnessPopoverViewTest.js', included: false },
            {pattern: 'test/tests-requireJS/views/popover/connectorFaceviewViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/popover/threeDviewViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/popover/basicPopoverViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/popover/customDataViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/popover/diagrams/diagramPopoverItemViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/popover/language/languagePopoverItemViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/popover/reports/reportsPopoverItemViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/popover/print/printOptionsPopoverItemViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/popover/relatedData/relatedDataPopoverViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/Views/Component/RenderConnectivityTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/contentpanel/SVGContentPanelTest.js', included: false},
            {pattern: 'test/tests-requireJS/OptionExpressionTest.js', included: false},
            { pattern: 'test/tests-requireJS/SVGEventHandlerTest.js', included: false },
            { pattern: 'test/tests-requireJS/rework/dao/rapidAuthor3DViewsTest.js', included: false },
            {pattern: 'test/tests-requireJS/UtilsTest.js', included: false},
            {pattern: 'test/tests-requireJS/TranslationUtilsTest.js', included: false},
            {pattern: 'test/tests-requireJS/textSplitterTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/systemsViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/informationListViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/designObjectsViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/ListViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/ListViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/navigationPanelViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/contentpanel/toolbar/contentToolBarTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/contentpanel/toolbar/systemToolBarTest.js', included: false},
            {pattern: 'test/tests-requireJS/filters/languageDataLoaderTest.js', included: false},
            // { pattern: 'test/tests-requireJS/filters/languageTranslationTest.js', included: false },
            {pattern: 'test/tests-requireJS/filters/languageTranslatorTest.js', included: false},
            {pattern: 'test/tests-requireJS/filters/vinFilterTest.js', included: false},
            {pattern: 'test/tests-requireJS/filters/configurationFilterTest.js', included: false},
            {pattern: 'test/tests-requireJS/filters/languageFilterTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/zoomToolBarViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/rework/dao/objectDataLoaderTest.js', included: false},
            {pattern: 'test/tests-requireJS/rework/dao/locationViewsTest.js', included: false},
            {pattern: 'test/tests-requireJS/rework/dao/utilitiesTest.js', included: false},
            {pattern: 'test/tests-requireJS/componentRouterTest.js', included: false},
            {pattern: 'test/tests-requireJS/vin/VINSearchHandlerTest.js', included: false}, // TODO: keep an eye
            {pattern: 'test/tests-requireJS/print/printTest.js', included: false},
            {pattern: 'test/tests-requireJS/print/printIntroductionTest.js', included: false},
            {pattern: 'test/tests-requireJS/reportHandlerTest.js', included: false},
            {pattern: 'test/tests-requireJS/contentPanel/contentPanelTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/popover/PopoverViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/customProjectDataListViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/vinFilterViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/tooltipTest.js', included: false},
            {pattern: 'test/tests-requireJS/collections/popover/PrintContentCollectionTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/popover/devicePopoverItemViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/packageViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/packagesViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/rework/dao/PathResolverTest.js', included: false},
            {pattern: 'test/tests-requireJS/highlighting/CrosshighlightHandlerTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/contentpanel/HarnessDiagramPanelTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/contentpanel/designReportPanelTest.js', included: false},
            {pattern: 'test/tests-requireJS/layoutManagerTest.js', included: false},
            {pattern: 'test/tests-requireJS/attributeParserTest.js', included: false},
            {pattern: 'test/tests-requireJS/eventHandlers/docReqHandlerTest.js', included: false},
            {pattern: 'test/tests-requireJS/svgloading/svgDetailPanelTest.js', included: false},
            {pattern: 'test/tests-requireJS/svgloading/TwoDSVGEventHandlerTest.js', included: false},
            {pattern: 'test/tests-requireJS/signaltrace/SignalRendererTest.js', included: false},
            //{pattern: 'test/tests-requireJS/popout/popoutHandlerTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/renderconnectivity/buildBtnViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/appNameAndLogo/appNameAndLogoViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/projectsViewTemplateTest.js', included: false},
            {pattern: 'test/tests-requireJS/vin/optionFilterPanelTest.js', included: false},
            {pattern: 'test/tests-requireJS/routerTest.js', included: false},
            // {pattern: 'test/tests-requireJS/svg/ZoomAndPanHandlerTest.js', included: false},
            {pattern: 'test/tests-requireJS/svg/SelectedObjectsStoreTest.js', included: false},
            {pattern: 'test/tests-requireJS/svg/SVGTransformModelTest.js', included: false},
            {pattern: 'test/tests-requireJS/filters/filteredDocFinderTest.js', included: false},
            {pattern: 'test/tests-requireJS/filters/documentContentBasedFilterTest.js', included: false},
            {pattern: 'test/tests-requireJS/templates/printTemplateTest.js', included: false},
            {pattern: 'test/tests-requireJS/templates/warningTemplateTest.js', included: false},
            {pattern: 'test/tests-requireJS/rework/dao/xmlDataLoaderImplTest.js', included: false},
            {pattern: 'test/tests-requireJS/collections/harnessLayoutsTest.js', included: false},
            {pattern: 'test/tests-requireJS/templates/wiresViewsTemplateTest.js', included: false},
            {pattern: 'test/tests-requireJS/templates/paginatedListGroupTest.js', included: false},
            {pattern: 'test/tests-requireJS/templates/informationTemplateTest.js', included: false},
            {pattern: 'test/tests-requireJS/templates/packageInfoViewTemplateTest.js', included: false},
            {pattern: 'test/tests-requireJS/templates/flatListTemplateTest.js', included: false},
            {pattern: 'test/tests-requireJS/templates/attributesTemplateTest.js', included: false},
            {pattern: 'test/tests-requireJS/templates/basicListItemTemplateTest.js', included: false},
            {pattern: 'test/tests-requireJS/templates/twoDLocationsTemplateTest.js', included: false},
            {pattern: 'test/tests-requireJS/templates/multipleListItemsTemplateTest.js', included: false},
            {pattern: 'test/tests-requireJS/templates/packagesTemplateTest.js', included: false},
            {pattern: 'test/tests-requireJS/routers/harnessLayoutDiagramRouterTest.js', included: false},
            {pattern: 'test/tests-requireJS/templates/popupTemplateTest.js', included: false},
            {pattern: 'test/tests-requireJS/LoadMaskTest.js', included: false},
            {pattern: 'test/tests-requireJS/filehandlers/systemSVGFileHandlerTest.js', included: false},
            {pattern: 'test/tests-requireJS/filehandlers/effectivitySetterTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/systemsAsTreeViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/treeViewHelperTest.js', included: false},
            {pattern: 'test/tests-requireJS/collections/p/c/localConfigurationsTest.js', included: false},
            {pattern: 'test/tests-requireJS/collections/p/c/XrefBuilderViewTest.js', included: false},
            {pattern: 'test/tests-requireJS/views/baseInteractiveBuilderTest.js', included: false},
            {pattern: 'test/tests-requireJS/templates/ConfigPopupBtnControlsTemplateTest.js', included: false},
            {pattern: 'test/tests-requireJS/routers/projectDataRouterTest.js', included: false},
            {pattern: 'test/tests-requireJS/routers/systemRouterTest.js', included: false},
            {pattern: 'test/tests-requireJS/models/configurationsModelTest.js', included: false},
            {pattern: 'test/tests-requireJS/documentObject/documentObjectPopoverTest.js', included: false},
            {pattern: 'test/tests-requireJS/documentObject/documentObjectPopover2Test.js', included: false},
            {pattern: 'test/tests-requireJS/rework/dao/utilitiesTest.js', included: false },
            {pattern: 'test/noLicenceTest.js', included: false },
            {pattern: 'test/tests-requireJS/preferencesTest.js', included: false},
            {pattern: 'test/tests-requireJS/models/store/CookieBasedePersistenceModelTest.js', included: false},
            {pattern: 'test/tests-requireJS/models/UserSessionTest.js', included: false},
        ],

        plugins: [
            'karma-junit-reporter',
            'karma-chrome-launcher',
            'karma-firefox-launcher',
            'karma-requirejs',
            'karma-safari-launcher',
            'karma-ie-launcher',
            'karma-opera-launcher',
            'karma-script-launcher',
            // 'karma-jasmine-jquery',
            'karma-jasmine',
            'karma-htmlfile-reporter',
            //If you see any jasmine matchers error when running tests, it could be version issue with karma-jasmine.
            //With karma 0.12.3/0.12.16, use karma-jasmine 0.2.2 - npm install -g karma-jasmine@0.2.2.
            'karma-ng-html2js-preprocessor',
            'karma-junit-reporter',
            'karma-coverage'
        ],

        // list of files / patterns to exclude
        exclude: [],


        // preprocess matching files before serving them to the browser
        // available preprocessors: https://www.npmjs.com/search?q=keywords:karma-preprocessor
        preprocessors: {
            '**/s/collections/**/*.js': ['coverage'],
            '**/s/custom/**/*.js': ['coverage'],
            '**/s/documentObject/**/*.js': ['coverage'],
            '**/s/documentRequestHandler/**/*.js': ['coverage'],
            '**/s/filehandlers/**/*.js': ['coverage'],
            '**/s/filters/**/*.js': ['coverage'],
            '**/s/illustrator/**/*.js': ['coverage'],
            '**/s/models/**/*.js': ['coverage'],
            '**/s/reports/**/*.js': ['coverage'],
            '**/s/reWork/**/*.js': ['coverage'],
            '**/s/routers/**/*.js': ['coverage'],
            '**/s/utilities/**/*.js': ['coverage'],
            '**/s/viewModels/**/*.js': ['coverage'],
            '**/s/views/**/*.js': ['coverage'],
            '**/s/*.js': ['coverage']
        },


        // test results reporter to use
        // possible values: 'dots', 'progress'
        // available reporters: https://www.npmjs.com/search?q=keywords:karma-reporter
        reporters: ['progress', 'coverage', 'html'],


        // web server port
        port: 9876,


        coverageReporter: {
            type: 'html',
            dir: '../../../../../../../../../../chs_home/bld/SmartClient/coverage/',
            subdir: '.',
        },

        htmlReporter: {
            outputFile: '../../../../../../../../../../chs_home/bld/SmartClient/summary/index.html',
            // Optional
            pageTitle: 'capital-webapp-distribution',
            subPageTitle: 'Smart client Unit Tests',
            groupSuites: true,
            useCompactStyle: true,
            useLegacyStyle: true,
            showOnlyFailed: false
        },

        // enable / disable colors in the output (reporters and logs)
        colors: true,


        // level of logging
        // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
        logLevel: config.LOG_INFO,


        // enable / disable watching file and executing tests whenever any file changes
        autoWatch: false,


        // start these browsers
        // available browser launchers: https://www.npmjs.com/search?q=keywords:karma-launcher
        browsers: ['ChromeHeadless'],


        // Continuous Integration mode
        // if true, Karma captures browsers, runs the tests and exits
        singleRun: true,

        // Concurrency level
        // how many browser instances should be started simultaneously
        concurrency: 1
    })
}
