package chs.caplets.shared;

public enum UserActionFailureReason
{
	STAMPDELETEDINANOTHERSERSESSION,
	STAMPLOCKERROR,
	STAMPCANNOTBELOADED,
	STAMPMOVEDTOANOTHERSESSION,
	DUPLICATESYMBOLNAME,
	DUPLICATEBORDERNAME,
	IGNOREFAILURE
}