# Navigation Panel Display
introduction-page = Information
Signal = Signal
report = Reports
harness = Harnesses
globalreports = Reports
system = Flows
HarnessLayouts = Harness Diagrams
faultcode = Fault Codes
diagnostics = Diagnostics
WiresTitle = Wires
GroundDevicesTitle = Grounds
InlinesTitle = Inlines
SplicesTitle = Splices
MulticoresTitle = Multicores
previousItems = Previous....
nextItems = Next....
FilterMenuTitle = Select Panel
FaceViewCommonTitle = Face View -
Filter = Search
Enter text and press Enter key to search in Navigation panel = Enter text and press Enter key to search in Navigation panel
DataLoadFailureMsg = Failed to load data
GroundsTitle = Grounds
renderConnectivityHeader=Render Connectivity
Full Instance=Full Instance
Set default zoom percentage=Set default zoom percentage
Zoom to fit=Zoom to fit
Zoom to default=Zoom to default
Zoom Selected=Zoom Selected

#Messages which are common to both  Navigation panel display and popup menus
ConnectorTitle = Connectors
DevicesTitle = Steps
SignalTitle = Signals
locationViews = Location Views
Build=Build

# Print Related Messages
printMsg = Print Items
Print = Print
PrintSelection = Print Selection
PrintAll = Print All
PrintOptionsMenuTitle = Print Options
PrintWindowLabel = Print Items
printSelectionAlert=Select at least one item from the list
NumberOfPages=Number Of Pages



#Package Selection
PackageSelectionMenuTitle = Settings
projects = Projects

#VIN filtering related messages
Login = Login
Username = Username
Password = Password
nousernamepassowrdentered = Please Enter Username and Password
nodatafoundforvin=No data found for the vin.
servererror=Can't connect to vin server.
wrongusernamepassord=Username or Password is wrong.
noserverurlfilefound=vin server configuration file not found
inValidSaop=Error : In-Valid SOAP request is sent
inValidUser=Username/Password is not entered correctly
noVinOptionsFound=No data found for entered VIN
noVinFileFound=Server Error :  VIN mapping file does not exists
inValidVinFile=Server Error :  VIN mapping file is not valid
failedToConnectToServer=Server Error : Failed to connect to server
inValidSOAPResponse=Server Error : SOAP Response sent from server is invalid
wrongProxyPort=Proxy port specified in config.xml file is wrong
wrongServerUrl=Server Error : could not connect to server url specified in config.xml
internalServerError=Internal Server Error
noUsersFileFound=userNames.txt file is missing on server
appletInitializing=Applet is initializing...
fetchingvindata=Fetching VIN data from the server..
EnterVintext = Choose Flow
javanotinstalled = Product requires Java 1.6_19 or higher. Download latest version of java from
Cancel = Cancel

# Individual System Related and pop up menu related
DiagramMenuTitle = Select Diagram
relatedDataMsg=Related Data
ReportMenuTitle = Select Report
ConnectorsTitle = Connectors
DeviceTitle = Steps
AttributesTitle=Overview
SystemDataTitle = System Data
XRefTitle = Links
FaceViewTitle = Face Views
ConnectorViewsTitle=Connector Views
LocationViewTitle = 3D Location Views
RapidAuthor3DViewTitle = Rapid Author 3D Location Views
TwoDLocationViewTitle = 2D Location Views
TwoDLocationSystemsTitle = Links
OptionsTitle=Applicability
ConfigurationsTitle =  Configurations
ConfigurationFilterTitle = Configuration Filter
selectReports = Select Reports
selectDiagrams = Select Diagrams
Popout = Pop out
Restore = Restore
Maximize = Maximize
Close = Close
Language = Language:
Redraw = Redraw
groundAndPowerSignalPanelHeader = Ground and Power Signal
Diagrams=Diagrams
Reports=Reports
RelatedData=Related Data
Signal Path=Signal path
signalTraceTitle=Display Signal Path
fullInstanceTitle=Show Full Symbol
groundAndPowerSignalTitle=Show Ground and Power Signal
FilterLabel = Search

# Langdictionary related messages
langDictionaryFailedToLoadMsg = Language Dictionary Failed To Load
ChooseLanguageMenuTitle = Choose Language

#General Status Message which will be used at different levels
tooManyResults = Too Many Results
statusMsgForPlugins= Loading 
statusMsgForPluginsAfterLoad= Success 
statusMsgForSVG = Loading SVG
statusMsgForSVGAfterLoad = SVG Loading Finish
statusMsgFor2DSVG = Loading Location Views
statusMsgFor2DSVGAfterLoad = Location Views loaded
statusMsgForFaultCodes = Loading FaultCodes
statusMsgForFaultCodesAfterLoad = FaultCodes loaded
statusMsgForSearchIndexing = Search indexing is in progress. Some results may be temporarily unavailable.
reportsLoading = Loading System Report
reportsLoadingFail = Failed to load System Report
reportsAfterLoading = Reports Loading Finish
faceViewsLoading = Loading FaceViews
afterFaceViewsLoading = FaceViews loaded
faceviewLoadingFail = Failed to load FaceViews
customeObjectData = Custome Object Data
systemMsg = Systems
HotSpotElementTagName = hotspot
TextElementTagName = text
ProjectPackageLoadingFailureMsg = Failed to load Project Details
LocationViewsLoadingFailureMsg = Failed to load Location Views
SchematicLoadingFailureMsg = Failed to load Schematics
DevicesLoadingFailureMsg = Failed to load Devices
ConnectorsLoadingFailureMsg = Failed to load Connectors
ObjectDetailsLoadingFailureMsg = Failed to load Object details
ThreeDLoadingFailureMsg = Failed to load 3 D Views
AttributesLoadFailMsg = Failed to load Attributes
DataRepoConfigurationErrorMsg = The configured Data Repository location does not contain any valid {app} packages.<br>Please have it reconfigured in the app's configuration files, so it points to a valid location, and then click "Try Again".
NoValidPacketAvailableMsg = No valid {app} packages available.<br> Please check you have a valid packet(s) present at data directory, and then click "Try Again".
UnZippedPackagesInRepoErrorMsg = The configured Data Repository location contains un-zipped packages.<br>Please have it reconfigured in the app's configuration files, so it points to a repository with zipped packages, and then click "Try Again". 
PackageDeletedOrMovedWarningMsg=Selected package does not exist. It may have been moved or deleted


#Fault Code Report
FaultCodeObjectNameColumnTitle=Object Name
FaultCodeSystemColumnTitle=System
pressEnterAndHitEnterKey=Enter text to filter then press enter key

PDFCantBeOpenedInternally = PDFs can't be opened from within the application.
PDFOpenExternally = Open PDF externally

#first page related
NavigationPanelToggleToolTip=Toggle navigation panel
SettingsPopoverViewTitle = Settings
SystemScopePanelTitle = System Scope
SystemScopeDesignsItemTitle = Designs
SystemScopeDiagramsItemTitle = Diagrams
LanguagesPanelTitle = Languages
Open=Open
ProjectsPageClickTip=<em>Click</em> to see additional details about the package.
ProjectsPageDoubleClickTip=<em>Double-click</em> to open the package.
PackageDescriptionUnavailable=No description has been provided for the package.
SwitchLanguageMenuTitle=Switch Language


#Projects Popover and other messages
ProjectsPopoverViewTitle = Select Project
DiagramsButtonTitle=Diagrams
DiagramsButtonTooltip = Select Diagram
DiagramsPopoverViewTitle = Select Diagram
IncorrectLicenseMessage = Unable to open packet. This content can only be viewed using {app}.
ProjectsMenuItemTitle = Settings
RenderConnectivityButtonTitle = Build
RelatedDataButtonTitle = Steps
RelatedDataButtonToolTip = Steps
RelatedDataPopoverViewTitle = Steps
ReportsButtonTitle = Reports
ReportsButtonToolTip = Select Report
ReportsPopoverViewTitle = Select Report
SettingsMenuItemTitle = Settings
BackgroundColorButtonTitle = Select Background Color
UnavailableLicenseMessage = Unable to open packet. There is no {app} license available.
Connector=Connector
Device=Step:-
Wire=Wire
Net=Net
Cavity=Cavity
Multicore=Multicore
Ground=Ground
Splice=Splice
Assembly=Assembly
Shield=Shield
Highway=Highway
SingleLine=Single Line
Overbraid=Overbraid

#diagnosics
DiagnosticPanel.Finish = FINISH
DiagnosticPanel.GoTo = Go To
DiagnosticPanel.NotePrefix = Note:

# ColorsPopover
colorspopover.title = Select Background Color
colorspopover.palettepanel.title = Background Colors
colorspopover.palettepanel.defaultcolor.title = Reset to Default
colorspopover.historypanel.title = Recent Colors
#Navigation between different face view symbols
FaceViewButtonTitle=View
FaceViewButtonToolTip=Navigate to different connector symbols
#Capital Illustrator
Designs=Designs
# Capital Change Explorer package
Search=Search
Old=(Old)
New=(New)

Links to Videos = Videos
Links to Documents = Documents
Links to Websites = Links
Links to Diagrams = Flows
Flow Tables = Flow Tables
Table of Contents = Table Of Contents
Packages=Packages
NonEffectivityProjectSearchTextPlaceHolder=Type your search here...
FilterPlaceholderText=Search

